<robot name="leobot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find leobot_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/common.urdf.xacro"/>
  <!--<xacro:include filename="$(find leobot_description)/urdf/sensors/hokuyo.urdf.xacro"/>-->
  <!--<xacro:include filename="$(find leobot_description)/urdf/wheels.urdf.xacro"/>-->

  <xacro:property name="base_radius" value="0.25"/>
  <xacro:property name="base_width" value="0.7"/>
  <xacro:property name="base_length" value="1.132"/>
  <xacro:property name="base_height" value="0.4"/>
  <xacro:property name="safety_width" value="0.03"/>

  <xacro:property name="distance_between_wheels" value="0.55"/>
  <xacro:property name="tower_height" value="1.125"/>
  <xacro:property name="head_height" value="0.1"/>

  <xacro:property name="caster_radius" value="0.05"/>
  <xacro:property name="caster_mass" value="10"/>

  <xacro:property name="wheel_width" value="0.035"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_mass" value="10"/>
  <xacro:property name="wheel_position_x" value="-0.35"/>
  <xacro:property name="wheel_position_z" value="0.02"/>
  <xacro:property name="caster_wheel_position_x" value="-1.0"/>
  <xacro:property name="caster_wheel_position_z" value="-0.04"/>

  <xacro:property name="bearing_radius" value="0.01"/>

  <link name="base_link">
    <visual>
      <xacro:box_geometry width="1" height="1" depth="1"/>
      <xacro:navajo_white_material/>
    </visual>
    <xacro:box_collision width="1" height="1" depth="1"/>
    <xacro:box_inertia mass="10" width="1" height="1" depth="1"/>
  </link>

  <link name="wheel_FR">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://leobot_description/meshes/Mecanum_Wheel_01.STL" scale="1 1 1"/>
      </geometry>
      <xacro:navajo_white_material/>
    </visual>
    <collision>
      <origin xyz="${-base_length/2} 0 ${base_height + tower_height/2} " rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="10" radius="${base_radius}" height="${base_height}"/>
  </link>

  <link name="wheel_FL">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://leobot_description/meshes/Mecanum_Wheel_01.STL" scale="1 1 1"/>
      </geometry>
      <xacro:navajo_white_material/>
    </visual>
    <collision>
      <origin xyz="${-base_length/2} 0 ${base_height + tower_height/2} " rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="10" radius="${base_radius}" height="${base_height}"/>
  </link>

  <link name="wheel_RL">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://leobot_description/meshes/Mecanum_Wheel_02.STL" scale="1 1 1"/>
      </geometry>
      <xacro:navajo_white_material/>
    </visual>
    <collision>
      <origin xyz="${-base_length/2} 0 ${base_height + tower_height/2} " rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="10" radius="${base_radius}" height="${base_height}"/>
  </link>

  <link name="wheel_RR">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://leobot_description/meshes/Mecanum_Wheel_02.STL" scale="1 1 1"/>
      </geometry>
      <xacro:navajo_white_material/>
    </visual>
    <collision>
      <origin xyz="${-base_length/2} 0 ${base_height + tower_height/2} " rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="10" radius="${base_radius}" height="${base_height}"/>
  </link>


  <joint name="base_link_wheel_FR_joint" type="continuous">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_FL" />
  </joint>

  <joint name="base_link_joint_wheel_FL_joint" type="continuous">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_FR" />
  </joint>


  <joint name="base_link_joint_wheel_RL_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_RL" />
  </joint>

  <joint name="base_link_joint_wheel_RR_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_RR" />
  </joint>


  <link name="camera_left_link">
    <visual>
      <xacro:box_geometry width="0.05" height="0.05" depth="0.05"/>
      <xacro:green_material/>
    </visual>
    <xacro:box_collision width="0.05" height="0.05" depth="0.05"/>
    <xacro:box_inertia mass="0.1" width="0.05" height="0.05" depth="0.05"/>
  </link>

  <joint name="camera_left_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.075 0.075"/>
    <parent link="base_link"/>
    <child link="camera_left_link"/>
  </joint>

  <link name="camera_right_link">
    <visual>
      <xacro:box_geometry width="0.05" height="0.05" depth="0.05"/>
      <xacro:green_material/>
    </visual>
    <xacro:box_collision width="0.05" height="0.05" depth="0.05"/>
    <xacro:box_inertia mass="0.1" width="0.05" height="0.05" depth="0.05"/>
  </link>

  <joint name="camera_right_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 -0.075 0.075"/>
    <parent link="base_link"/>
    <child link="camera_right_link"/>
  </joint>

</robot>