<?xml version="1.0"?>
<robot name="leobot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find leobot_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/sensors/hokuyo.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/wheels.urdf.xacro"/>

  <xacro:property name="base_width" value="0.7"/>
  <xacro:property name="base_length" value="1.132"/>
  <xacro:property name="base_height" value="0.4"/>
  <xacro:property name="safety_width" value="0.03"/>

  <xacro:property name="distance_between_wheels" value="0.55"/>
  <xacro:property name="tower_height" value="1.125"/>
  <xacro:property name="head_height" value="0.1"/>

  <xacro:property name="caster_radius" value="0.05"/>
  <xacro:property name="caster_mass" value="10"/>

  <xacro:property name="wheel_width" value="0.035"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_mass" value="10"/>
  <xacro:property name="wheel_position_x" value="-0.35"/>
  <xacro:property name="wheel_position_z" value="0.02"/>
  <xacro:property name="caster_wheel_position_x" value="-1.0"/>
  <xacro:property name="caster_wheel_position_z" value="-0.04"/>

  <xacro:property name="bearing_radius" value="0.01"/>

  <link name="base_link"/>

  <link name="chassis">
    <visual>
      <geometry>
        <mesh filename="package://leobot_description/meshes/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <xacro:navajo_white_material/>
    </visual>
  </link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <link name="chassis_inertia">
    <collision>
      <origin xyz="${-base_length/2} 0 ${base_height/2 - safety_width}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length + safety_width} ${base_width + safety_width} ${base_height + safety_width}"/>
      </geometry>
    </collision>
    <xacro:box_inertia mass="10.0" width="${base_width}" depth="${base_length}" height="${base_height}"
                       x="${-base_length/2}" z="${base_height/2}"/>
  </link>

  <joint name="chassis_inertia_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="chassis_inertia" />
  </joint>

  <xacro:caster_wheel radius="${caster_radius}" mass="${caster_mass}" x="${caster_wheel_position_x}"
                      z="${caster_wheel_position_z}"/>
  <xacro:standard_wheel prefix="left" direction="1.0" bearing_radius="${bearing_radius}" radius="${wheel_radius}"
                        width="${wheel_width}" mass="${wheel_mass}" distance_between_wheels="${distance_between_wheels}"
                        x="${wheel_position_x}" z="${wheel_position_z}"/>
  <xacro:standard_wheel prefix="right" direction="-1.0" bearing_radius="${bearing_radius}" radius="${wheel_radius}"
                        width="${wheel_width}" mass="${wheel_mass}" distance_between_wheels="${distance_between_wheels}"
                        x="${wheel_position_x}" z="${wheel_position_z}"/>
  <xacro:lidar_hokuyo parent_link_name="chassis"/>


  <link name="tower_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://leobot_description/meshes/tower.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <xacro:navajo_white_material/>
    </visual>
    <collision>
      <origin xyz="${-base_length/2} 0 ${base_height + tower_height/2} " rpy="0 0 0"/>
      <geometry>
        <box size="${base_length + safety_width} ${base_width + safety_width} ${tower_height + safety_width}"/>
      </geometry>
    </collision>
    <xacro:box_inertia mass="3.0" width="${base_width}" depth="${base_length}" height="${tower_height}"/>
  </link>

  <joint name="tower_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="tower_link"/>
  </joint>

  <link name="head_link">
    <visual>
      <origin xyz="0.75 0 -${base_height+tower_height+head_height/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://leobot_description/meshes/head.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <xacro:navajo_white_material/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${head_height*2}" radius="${base_width/2}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia mass="1" radius="${base_width/2}" height="${head_height*2}"/>
  </link>

  <joint name="head_link_joint" type="revolute">
    <origin rpy="0 0 0" xyz="-0.75 0 ${base_height+tower_height+head_height/2}"/>
    <axis xyz="0 0 1" />
    <parent link="tower_link"/>
    <child link="head_link"/>
    <limit effort="10" velocity="10" lower="${-pi/2}" upper="${pi/2}" />
  </joint>

  <transmission name="head_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="head_link_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="head_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="camera_left_link">
    <visual>
      <xacro:box_geometry width="0.05" height="0.05" depth="0.05"/>
      <xacro:green_material/>
    </visual>
    <xacro:box_collision width="0.05" height="0.05" depth="0.05"/>
    <xacro:box_inertia mass="0.1" width="0.05" height="0.05" depth="0.05"/>
  </link>

  <joint name="camera_left_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0.075 0.075"/>
    <parent link="head_link"/>
    <child link="camera_left_link"/>
  </joint>

  <link name="camera_right_link">
    <visual>
      <xacro:box_geometry width="0.05" height="0.05" depth="0.05"/>
      <xacro:green_material/>
    </visual>
    <xacro:box_collision width="0.05" height="0.05" depth="0.05"/>
    <xacro:box_inertia mass="0.1" width="0.05" height="0.05" depth="0.05"/>
  </link>

  <joint name="camera_right_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 -0.075 0.075"/>
    <parent link="head_link"/>
    <child link="camera_right_link"/>
  </joint>

</robot>