<robot name="leobot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find leobot_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/sensors/camera.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/sensors/hokuyo.urdf.xacro"/>
  <xacro:include filename="$(find leobot_description)/urdf/wheels.urdf.xacro"/>

  <xacro:property name="base_width" value="0.5"/>
  <xacro:property name="base_length" value="0.3"/>
  <xacro:property name="base_height" value="0.54"/>
  <xacro:property name="base_mass" value="10"/>

  <xacro:property name="neck_width" value="0.04"/>
  <xacro:property name="neck_length" value="0.04"/>
  <xacro:property name="neck_height" value="1.45"/>
  <xacro:property name="neck_mass" value="1.0"/>

  <xacro:property name="head_width" value="0.04"/>
  <xacro:property name="head_length" value="0.04"/>
  <xacro:property name="head_height" value="0.29"/>
  <xacro:property name="head_mass" value="0.5"/>

  <link name="base_link">
    <visual>
      <xacro:box_geometry width="${base_width}" height="${base_height}" depth="${base_length}"/>
      <xacro:green_material/>
    </visual>
    <xacro:box_collision width="${base_width}" height="${base_height}" depth="${base_length}"/>
    <xacro:box_inertia width="${base_width}" height="${base_height}" depth="${base_length}" mass="${base_mass}"/>
  </link>

  <link name="neck_link">
    <visual>
      <xacro:box_geometry width="${neck_width}" height="${neck_height}" depth="${neck_length}"/>
      <xacro:red_material/>
    </visual>
    <xacro:box_collision width="${neck_width}" height="${neck_height}" depth="${neck_length}"/>
    <xacro:box_inertia width="${neck_width}" height="${neck_height}" depth="${neck_length}" mass="${head_mass}"/>
  </link>

  <joint name="base_neck_joint" type="fixed">
    <origin rpy="${pi/2} 0  0" xyz="0 ${-base_width/2 - neck_width} ${-base_length/2 + neck_height / 2 }"/>
    <parent link="base_link"/>
    <child link="neck_link"/>
  </joint>

  <link name="head_link">
    <visual>
      <xacro:box_geometry width="${head_width}" height="${head_height}" depth="${head_length}"/>
      <xacro:blue_material/>
    </visual>
    <xacro:box_collision width="${head_width}" height="${head_height}" depth="${head_length}"/>
    <xacro:box_inertia width="${head_width}" height="${head_height}" depth="${head_length}" mass="${head_mass}"/>
  </link>

  <joint name="neck_head_joint" type="fixed">
    <origin rpy="${pi/2} 0  0" xyz="0 ${neck_height/2 + head_width/2} ${neck_length/2 - head_height/2}"/>
    <parent link="neck_link"/>
    <child link="head_link"/>
  </joint>

  <xacro:fish_camera prefix = "left" parent_link_name="head_link" parent_height="${head_height}" parent_width = "${head_width}" side="1"/>
  <xacro:fish_camera prefix = "right" parent_link_name="head_link" parent_height="${head_height}"  parent_width = "${head_width}" side="-1"/>

  <xacro:lidar_hokuyo parent_link_name="base_link" parent_height="${base_length}"/>

  <xacro:mecanum_wheel prefix="FR" wheel_type="1" side="1" position="1" parent_length="${base_width}" parent_height="${base_height}" parent_width="${base_length}"/>
<!--  <xacro:macro name="mecanum_wheel" params="link_name mesh_file radius width *origin">
    <link name="${link_name}">
      <visual>
        <xacro:insert_block name="origin"/>
        <geometry>
          <mesh filename="${mesh_file}" scale="1 1 1"/>
        </geometry>
        <xacro:navajo_white_material/>
      </visual>
      <collision>
        <xacro:insert_block name="origin"/>
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia mass="10" radius="${radius}" height="${width}"/>
    </link>
  </xacro:macro>-->


  <!--<xacro:macro name="leobot_mecanum_wheel" params="name variant origin_x origin_y">
    <xacro:mecanum_wheel link_name="wheel_${name}"
                         mesh_file="package://leobot_description/meshes/Mecanum_Wheel_0${variant}.STL"
                         radius="${wheel_radius}" width="${wheel_width}">
      <origin xyz="${origin_x * base_width/2} ${origin_y * base_length/2}"
              rpy="${pi/2} 0 0"/>
    </xacro:mecanum_wheel>
  </xacro:macro>


  <xacro:leobot_mecanum_wheel name="FR" variant="1" origin_x="1"  origin_y="1"/>
  <xacro:leobot_mecanum_wheel name="FL" variant="1" origin_x="-1" origin_y="1"/>
  <xacro:leobot_mecanum_wheel name="RL" variant="2" origin_x="-1" origin_y="-1"/>
  <xacro:leobot_mecanum_wheel name="RR" variant="2" origin_x="1"  origin_y="-1"/>


  <joint name="base_link_wheel_FR_joint" type="continuous">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_FL" />
  </joint>

  <joint name="base_link_joint_wheel_FL_joint" type="continuous">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_FR" />
  </joint>


  <joint name="base_link_joint_wheel_RL_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_RL" />
  </joint>

  <joint name="base_link_joint_wheel_RR_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_RR" />
  </joint>
-->

</robot>