<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="hokuyo_radius" value="0.05"/>
    <xacro:property name="hokuyo_height" value="0.05"/>
    <xacro:property name="hokuyo_mass"   value="0.2"/>

    <xacro:macro name="lidar_hokuyo" params="parent_link_name parent_height">
        <link name="laser_link">
            <visual>
                <xacro:cylinder_geometry height="${hokuyo_height}" radius="${hokuyo_radius}"/>
                <xacro:green_material/>
            </visual>
            <xacro:cylinder_collision height="${hokuyo_height}" radius="${hokuyo_radius}"/>
            <xacro:cylinder_inertia mass="${hokuyo_mass}" height="${hokuyo_height}" radius="${hokuyo_radius}"/>
        </link>

        <joint name="laser_base_joint" type="fixed">
            <origin xyz="0 0 ${hokuyo_height/2 + parent_height/2}" rpy="0 0 0"/>
            <parent link="${parent_link_name}" />
            <child link="laser_link" />
        </joint>
    </xacro:macro>

</robot>