<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="motor_holder_radius" value="0.02"/>
    <xacro:property name="motor_holder_height" value="0.1"/>
    <xacro:property name="motor_holder_mass" value="0.8"/>
    <xacro:property name="mecanum_radius" value="0.1"/>
    <xacro:property name="mecanum_height" value="0.05"/>
    <xacro:property name="mecanum_mass" value="0.3"/>
    <xacro:macro name="mecanum_wheel"
                 params="prefix wheel_type side position parent_length parent_height parent_width">
        <link name="${prefix}_motor_holder">>
            <visual>
                <xacro:cylinder_geometry radius="${motor_holder_radius}" height="${motor_holder_height}"/>
                <xacro:blue_material/>
            </visual>
            <xacro:cylinder_collision radius="${motor_holder_radius}" height="${motor_holder_height}"/>
            <xacro:cylinder_inertia mass="${motor_holder_mass}" radius="${motor_holder_radius}" height="${motor_holder_height}"/>
        </link>

        <joint name="${prefix}_motor_holder_base_joint" type="fixed">
            <origin rpy="${pi/2} 0 0"
                    xyz="${position * (parent_width/2 - motor_holder_height/2)} ${position * parent_length} ${side * (parent_height/2 - motor_holder_radius/2)}"/>
            <parent link="base_link"/>
            <child link="${prefix}_motor_holder"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin rpy="${pi / 2} 0 0 " xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://leobot_description/meshes/Mecanum_Wheel_${wheel_type}.STL" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <xacro:cylinder_collision radius="${mecanum_radius}" height="${mecanum_height}"/>
            <xacro:cylinder_inertia mass="${mecanum_mass}" radius="${mecanum_radius}" height="${mecanum_height}"/>
        </link>

        <joint name="${prefix}_wheel_motor_joint" type="continuous">
            <origin rpy="0 0 0" xyz="0 0 ${side * mecanum_height/2}"/>
            <parent link="${prefix}_motor_holder"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 0 1"/>
        </joint>
        <transmission name="${prefix}_wheel_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_motor_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
                <motorTorqueConstant>1</motorTorqueConstant>
            </actuator>
        </transmission>
    </xacro:macro>

</robot>
