gazebo_ros_control:
  pid_gains:
    front_left_wheel_motor_joint:
      p: 100.0
      i: 1.0
      d: 0.1
    front_right_wheel_motor_joint:
      p: 100.0
      i: 1.0
      d: 0.1
    rear_left_wheel_motor_joint:
      p: 100.0
      i: 1.0
      d: 0.1
    rear_right_wheel_motor_joint:
      p: 100.0
      i: 1.0
      d: 0.1
